version: '3'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
    depends_on:
      - db
  db: 
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always